###################################
###################################
## Natural language Linter rules ##
###################################
###################################

rules:
  en-capitalisation:
    allowWords: ["html","htm","js","css","md"]

