###################################
###################################
## Natural language Linter rules ##
###################################
###################################

rules:
  terminology:
    skip: ["Link", "LinkExit", "Code", "CodeExit"]

