###################################
###################################
## Natural language Linter rules ##
###################################
###################################

rules:
  terminology:
    skip: ["BlockQuote", "Link", "LinkExit", "Code", "CodeExit"]
    exclude: ["HTML", "html", "HTM", "htm"]

